version: "3.7"

# https://nodered.org/docs/getting-started/docker
services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    networks:
      - node-red-net
    volumes:
      # it seems it doesn't work - `./volumes/node-red` is permanently empty
      - ./volumes/node-red:/data

networks:
  node-red-net: